base:
    environment:
     - DC_NAME=dc1
     - COLLECT_METRICS=false
     - FORWARD_TO_KAFKA=false
     - SKIP_PSWATCH=true
    dns: 127.0.0.1
    dns_search:
     - node.consul
     - service.consul
    privileged: true
