samza:
    image: qnib/u-samza
    hostname: samza
    container_name: samza
    environment:
     - BOOTSTRAP_CONSUL=true
     - RUN_SERVER=true
    ports:
     - 8500:8500
     - 8042:8042
     - 8088:8088

